---
baseURL: https://sonatype.github.io/ossindex-maven/
languageCode: en-us
title: "Sonatype OSS Index: Maven"
theme: dionysus

# Publish content to maven-standard-ish location for generated content
publishdir: ../../../target/hugo-public

params:
  inceptionYear: 2018
  footer_sections:
    - About
    - Resources
    - Legal

taxonomies:
  tag: tags
  category: categories

menu:
  footer_sections:
    - identifier: footer_about
      name: About
      weight: 1
    - identifier: footer_resources
      name: Resources
      weight: 2
    - identifier: footer_legal
      name: Legal
      weight: 3

outputs:
  # configure specific outputs for home page to include rss feeds and search index
  home:
   - html
   - rss
   - json

# Blackfriday options; see https://gohugo.io/content-management/formats/

# see https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji: true

# Highlight options; see https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences: true

# see https://xyproto.github.io/splash/docs/all.html
pygmentsStyle: manni
